# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Memoverkill
tagline:             'int $0x80'
description:         'Software Engineering might be science, but that''s not what I do. I''m a hacker, not an engineer - Jamie Zawinski. Follow me <a href="https://twitter.com/oshadhaviraj" target="_blank">@oshadhaviraj</a>.'
url:                 http://www.memoverkill.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Oshadha Gunawardena
  url:               https://twitter.com/oshadhaviraj
  email:             oshadha.rocky@gmail.com

# Custom vars
version:             1.0.0
